### ISSUE TITLE
Cannot connect after flashing

### ISSUE THREAD

**Issue by belowm** [lsochanowski/GoHeishaMon#15]
Hey, first of all, thanks creating this project!
I followed the installation process and observed the LED changes as described. I unplugged the pen driver after the white light turned off. 
Now, power is green, status is white, and link is green (blinking). Does this pattern indicate normal operation? 
Is wifi configuration still done via WPS? 
I tried connecting via LAN, but I don't get any IP assigned via DHCP. Assigning a static IP in the 192.168.1.x range didn't help either. Any hints are much appreciated. 

Thanks!

**Comment by MiG-41** [comment]
Led status sounds ok.

Regarding the connection , we assumed , that conection will be identical ,to one with was set during "normal" (Smart Cloud) setting.  
So no ,( in current version) , button WPS dont work ,when you run on GoHeishamon side.
Please set your destination conection first ,and then start GoHeishamon procedure. 
If you need change the connection ,the easiest way will be to go back to Service Cloud ( by pressing 3 buttons ) , and set destination conection there.

**Comment by belowm** [comment]
Thanks, I'll give this a try. I didn't imagine that wifi configuration is kept after flashing the firmware.

**Comment by MiG-41** [comment]
Problem is , that we very seldom receive a feedback.... In our cases works , and assuming that for others too :) 
Give feedback !  :)

**Comment by belowm** [comment]
Works great! Thanks man. I think the readme should include more detailed instructions for setting up. Maybe I can contribute? Closing this for now.

**Comment by MiG-41** [comment]
@belowm , if you have something to add , you are welcome to made a PR.
Thank you in advance !
