### ISSUE TITLE
SSH/Luci-Password?

### ISSUE THREAD

**Issue by basi0** [lsochanowski/GoHeishaMon#44]
I've successfully installed Goheishamon on my CZ-TAW1B, but want to access it via ssh or luci.

Both require a password for login - but it seems that the password is not in the documentation.

So - what is the default password?

**Comment by basi0** [comment]
Changed it via mqtt call:

mosquitto_pub -t "panasonic_heat_pump/commands/OSCommand" -m '/root/pass.sh <NEWPASS>' -h <BROKER IP>

**Comment by PiotrMarcinczyk-TomTom** [comment]
`GoHeishaMonpass` it's in the old version of README
