### ISSUE TITLE
No luci on system

### ISSUE THREAD

**Issue by Dario82** [lsochanowski/GoHeishaMon#9]
Hello,
I've upgrade with your firmware but I have only ssh...
How to connect to luci?

Thank you.

**Comment by MiG-41** [comment]
In web browser you should put ip address of CZ-TAW1 ,and luci should apear.

**Comment by Dario82** [comment]
I do it!
I have SSH only... MQTT ok.

**Comment by MiG-41** [comment]
Please try 1.0.134 realease , this one tested. Don't put dropbear file to drive (ssh is already included).
To test i ,go back first to SmartCloud ( simplest way to press three buttons ,when GoHeisha works and the other "side" with Smart Cloud strart). And then put 1.0.134 realease to drive ( optionally with config file). And  look.

**Comment by Dario82** [comment]
Only (release v. 1.0.134):
- openwrt-ar71xx-generic-cus531-16M-kernel.bin
- openwrt-ar71xx-generic-cus531-16M-rootfs-squashfs.bin
- GoHeishaMonConfig.new

on the drive?

**Comment by MiG-41** [comment]
yes.
BTW , you are not loosing much , becouse in luci you can only set a wireless comunication max , but it is courious ,why you don't have it...

**Comment by Dario82** [comment]
Must I add a "EnableCommand=true" on config?

**Comment by MiG-41** [comment]
you can . Probably it is not a must , but i'm not sure.

**Comment by Dario82** [comment]
I've pressed 3 button on the same time... nothing... How I can return to original firmware?

**Comment by MiG-41** [comment]
GoHeishaMon should be active when you press buttons. ( color of diode will be changed to veryfy it ).
You can do it manually in ssh giving commands:
fwupdate sw 
reboot

**Comment by Dario82** [comment]
Now... I don't have SSH, MQTT, WEB...

**Comment by MiG-41** [comment]
you should wait some minutes for ssh. 
Is the middle LED have the white color ?

**Comment by Dario82** [comment]
The middle led is white. I can only ping my device.
But, how this device can connect to my wlan without password? It uses the configuration in other side of original firmware?

**Comment by Dario82** [comment]
ssh: connect to host 192.168.10.17 port 22: Connection refused
...nothing...

**Comment by MiG-41** [comment]
Yes , the settings are generally identical for booth sides.
If LED is white ,then something is wrong with config file and conigurations ( GoHeishaMon starts , and stops).

**Comment by Dario82** [comment]
I've restarted the pump, on / off.
Now I have MQTT (data sent ok) but I don't have luci and ssh.
But I see a ESPxxxx Wifi, is it normal?

**Comment by MiG-41** [comment]
ESPxxx WiFi is not normal , but i doupt is comming from CZ-TAW1. Maybe you have somwhere such device ESP8266 or ESP32 ,with is additionally sending it ? 
In my small project i had same , used ESP8266 ,connecting to my router , but in the same time ESP8266 generate some ESPxxxnetwork , like here https://forum.arduino.cc/index.php?topic=501263.0

This is strange ,why ssh and web i have , and you don't....

**Comment by MiG-41** [comment]
When you have "EnableCommand=true" , can you listen topic in mqtt "panasonic_heat_pump/OSCommand/out" ( i.e. via mosquitto_sub) , and then send to topic "panasonic_heat_pump/OSCommand" command like "uptime" or "ls /tmp" to see if it works ?

**Comment by MiG-41** [comment]
Can you join to Slack communication , given in Readme.md in Heishamon project : https://github.com/Egyras/HeishaMon/tree/master/HeishaMon
would be easier to discuss

**Comment by lsochanowski** [comment]
i think it was resolved in newest version ssh  will work without configuring over mqtt
